{% set version = '0.13' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-repr
  version: {{ version|replace("-", "_") }}

source:
  fn: repr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/repr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/repr/repr_{{ version }}.tar.gz
  sha256: 8d3e1c01dfecaaf693c39c825a1073a4c7e019e960740a8346d9a75fb249a74c

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: methods, highr, Cairo, testthat
requirements:
  build:

  host:
    - r-base
    - r-base64enc
    - r-htmltools

  run:
    - r-base
    - r-base64enc
    - r-htmltools

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('repr')"           # [not win]
    - "\"%R%\" -e \"library('repr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=repr
  license: GPL-3
  summary: String and binary representations of objects for several formats / mime types.
  license_family: GPL3

extra:
  recipe-maintainers:
    - ocefpaf
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: repr
# Title: Serializable Representations
# Version: 0.13
# Authors@R: c( person('Philipp', 'Angerer', email = 'phil.angerer@gmail.com', role = c('aut', 'cre')), person('Thomas', 'Kluyver', email = 'thomas@kluyver.me.uk', role = 'aut'), person('Jan', 'Schulz', email = 'jasc@gmx.net', role = 'aut'), person('abielr', role = 'ctb'), person('Denilson', 'Figueiredo de Sa', role = 'ctb'), person('Jim', 'Hester', role = 'ctb'), person('karldw', role = 'ctb'), person('Carson', 'Sievert', role = 'ctb') )
# Maintainer: Philipp Angerer <phil.angerer@gmail.com>
# Description: String and binary representations of objects for several formats / mime types.
# Depends: R (>= 3.0.1)
# Imports: utils, grDevices, htmltools, base64enc
# Suggests: methods, highr, Cairo, testthat
# Enhances: data.table, dplyr, htmlwidgets
# License: GPL-3
# LazyData: true
# Encoding: UTF-8
# Collate: 'generics.r' 'options.r' 'package.r' 'repr_datatable.r' 'utils.r' 'repr_list.r' 'repr_vector.r' 'repr_factor.r' 'repr_function.r' 'repr_help_files_with_topic.r' 'repr_htmlwidget.r' 'repr_matrix_df.r' 'repr_packageIQR.r' 'repr_recordedplot.r'
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-04-14 14:29:21 UTC; phil
# Author: Philipp Angerer [aut, cre], Thomas Kluyver [aut], Jan Schulz [aut], abielr [ctb], Denilson Figueiredo de Sa [ctb], Jim Hester [ctb], karldw [ctb], Carson Sievert [ctb]
# Repository: CRAN
# Date/Publication: 2018-04-14 16:08:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
