travis:
  secure:
    BINSTAR_TOKEN: izj/JX6GAX1cE0jn4f6NraoY/jit1Pe8RmYbDJgIV/WCtpbATtJH/Ny9B8L9ZS8pfV6mbhQPiJ41yCnIPaBs9dncDhC+zJhZwGEz4d5lNK3/Uix9LbS5+Q9VQam9dKtcejDWXhyvrXOwClFMWpDJMxueguM+AXi9PDvDMUn9688U7C1pxt6xkDVjUAf4fahMgKf8QgSmA5E6boiRQglTIS32O6kKOniEM2sjkrUAWCg0QHV31L69k+8er9XUxLI2rR1Kq/2aoYZpv6rPZ8Heaqbq92RaXyAe+ar5Af5KZsY6XH1WT4OnY6v4G0tCzfJQ3euF0z2TjCjXygKqBfM6LttM1v17rD4IMABQqZN/kA/dnxB3sDMQiRSXooUDJkEOVQ8C0wUJhXDXxT+h+ecSns+coCIviI49ETpj2kX3p79tF1fuussNjHg3Kw0Y+1Ra4QnIWtzCWk7nWtp34suTEc59qXlZ81G9R1W2BYNNi2OVmTOdm8o9JglvpusdMhlMV4HWeNnenNY9ZCfKm3DiuroxGFm3LD/moY6ZcvSgcRguBuqrmunKMK0Hjx6tPcPyALBPt1Pcq43PGbe3okU7+yOPdoKMB9prpPn2truD1Anj2J3EyuDzZQivPTJwSvtoQGaB2tjf6jBVmrSj6gt7gmWO0BOEvXi67aWkfC/v7AY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
