travis:
  secure:
    BINSTAR_TOKEN: Pk7Jvq/gkfBgRRWdk8TyGYL7I7ViBkuimf+XYfqYBisGWWuIBYUpojm/XfkVcVxR33TVmJQIZyNGABRJyaIQfGXTLhNI48eJZF3WEXlr791/Zk51MVTo5nuvyZXzZOcs+2xI1yADiDzkNhwK1SjNBSHVJe9Px0mgrP5IRapWoMlt9AlB95rFrTuH24cvDxC3XjrrYe228P5WvObh8IBflQW+8LkR6k9DYdf7x8I//F7UIISL02BSc/BBtrgIFunP6flRJgT7/0v6oI6sdFCspcz530FZgB1pZQNB7GvmW5QiINoUY3sz/iSC/5G53xZZuckCm4qiX35BrlPdv56WuzsKRUBifbxAy1UlK3AaDtFuIMFfGHLb60qWSBsKR8KSPstEyD8MsNSdfKg8NFXz1kbuDK1gZ/KfBOrgYc9BzLKk9Ki+bbbucyEAg7yqE0XO5CpQVxZ3jsn8ZYudn975q5J8YRZEBUOQhE4gmzvMKV7lN/vIRWDwq7Lnx78/nzRVqWmwy18jLnr27Qtk+Yiy48M/DV+iO7dt3O3mBB56HT09HAmluplFCye8FSPQnwVa7XdqNFwlvBQb0Wu36EKJ+CkqlAYU/LGfYqUI+m6ztAxsAJrfRScase1J4PJSxKLOyq6g5GGf7sDd+cM1ORM2gbccQZBpjWo+LYkbBCSsUYg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
