travis:
  secure:
    BINSTAR_TOKEN: pSDRdYfMiuG8W/8HYnEkLCDG+YObjzcpg2+vGYxge7nKzEWjvxoHB4Krx0DDbUV12BNY9UL9n3NZGOrc6mNAcO7HVT4p5FeKmGBnzpxv4AmL6legr7Z+w+lvn6gBNebLAjoTLe1VNB4jetLO3mC/aEjXA//N9T5s2qE9EhLA/FZHchiH11JBFzh40h547D5I97PkYgTsiyNsTphypUb1isNBGJSeZNoo4LmEcA5TV51Q0DynwdrZvg0cUUzeReNdPUpn7kOP7cH7LMelK8fQnpQoQ2s73phXK8nk22o0RcWxzbUdBYix7cCecjF8NttWAUmr5FkbGcrFsuXVKTnsuSkp/7rpCaDMcXrjDwwZpBsVjwr5sQr4Uji2SFlUUi4yHV+gVJ/wnatsiD/zAcj5eR0Pl+sAu2LgWl5Z+JzIwNjrUexnJZP+yaEDqf+JIWFGd69MUjSJ03Y0N5fpkK5EmBJEfgdVd0g/fbjGBrMrM2UoG0s9iWTOwNtW+jZWZwEZZq7M+Y22lcssKhbzL8tXjeAUtNQ8BPQYgZ4RnZLcis7rs9upb3oJEFfusNneoqe+FvJszUe2rXYSUau51awPaLtPkbzgOI0QyPWlbcpn0ukfV5FH0kPO7VW7ib8eyMZgIKKeRf/FNr4kDYuXgQW6rZ3Pk1GWi2KZ/sfZ/ldJqUA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
